## Ordinal Encoding

In [36]:
import numpy as np
import pandas as pd

In [37]:
df = pd.read_csv('customer.csv')

In [38]:
df.sample(5)

    age gender   review education purchased
12   51   Male     Poor    School        No
45   61   Male     Poor        PG       Yes
15   75   Male     Poor        UG        No
35   74   Male     Poor    School       Yes
30   73   Male  Average        UG        No

In [39]:
df=df.iloc[:,2:]

In [40]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [56]:
from sklearn.preprocessing import OrdinalEncoder

In [57]:
X_train

     Alcohol  Malic acid
22     13.71        1.86
108    12.22        1.29
175    13.27        4.28
145    13.16        3.57
71     13.86        1.51
..       ...         ...
103    11.82        1.72
67     12.37        1.17
117    12.42        1.61
47     13.90        1.68
172    14.16        2.51

[124 rows x 2 columns]

In [48]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [55]:
oe.fit(X_train)

ValueError: could not convert string to float: 'Poor'